#!/bin/bash

alias g=git
alias main="git switch main"
alias commit="git commit"
alias git_branch="git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'"

alias m="mise run"
alias c="claude"

alias idea="open -a 'IntelliJ IDEA CE'"
alias rubymine="open -a 'RubyMine'"
alias studio="open -a 'Android Studio'"
alias xcode="open -a 'Xcode'"

