#!/bin/bash

alias chrome="open -a 'Google Chrome'"
alias idea="open -a 'IntelliJ IDEA CE'"
alias rubymine="open -a 'RubyMine'"
alias studio="open -a 'Android Studio Preview'"
alias xcode="open -a 'Xcode'"

