#!/bin/bash

# func
repo() {
  cd $(ghq list --full-path | fzf --reverse \
    --preview-window down:30 \
    --bind ctrl-d:preview-down \
    --bind ctrl-u:preview-up \
    --preview 'bat --color always {}/README.md')
}

pullstream() {
  echo "git fetch upstream"
  git fetch upstream
  echo "git rebase upstream/master"
  git rebase upstream/master
}

hi() {
  history | cut -c 8- | tac | fzf --reverse | pbcopy
  echo "copied"
}

