#!/bin/bash

# func
repo() {
  cd $(ghq list --full-path | fzf --reverse \
    --preview-window down:30 \
    --bind ctrl-d:preview-down \
    --bind ctrl-u:preview-up \
    --preview 'bat --color always {}/README.md')
}

