[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme='bubblegum'
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#branch#enabled = 0
  let g:airline#extensions#readonly#enabled = 0
  let g:airline#extensions#tabline#enabled = 1
  let g:airline_section_c = ''
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_auto_colors = 0
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=black
'''

[[plugins]] # color schema
repo = 'w0ng/vim-hybrid'
hook_add = '''
  colorscheme hybrid
  set background=dark
'''

[[plugins]] # 括弧補完
repo = "cohama/lexima.vim"

[[plugins]] # auto indent
repo = "Chiel92/vim-autoformat"

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_fmt_command = "goimports"
'''

[[plugins]] # go補完
repo = 'nsf/gocode'

[[plugins]] # 定義jump
repo = 'rogpeppe/godef'

[[plugins]] # syntax highlight
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # haskell
repo = 'eagletmt/neco-ghc'

[[plugins]] # haskell
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:python_host_prog='/usr/bin/python'
  let g:python3_host_prog='/opt/brew/bin/python3'
'''

[[plugins]] # 末尾spaceの可視化
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  nmap ; :Buffers
  nmap ' :Files
  nmap ,a :Ag
'''

[[plugins]] # snake_case CamelCaseのmotionに対応
repo = 'chaoren/vim-wordmotion'
hook_add = '''
  let g:wordmotion_spaces = '_-.'
'''

