#!/bin/bash

if [ ! -z "$1" ]; then
  if [[ "$1" == "." ]]; then
    git checkout .
  elif [[ "$1" == mine ]]; then
    GH_FORCE_TTY='100%' gh pr list --assignee @me --limit 100 |
      tail -n +4 |
      fzf --ansi \
        --preview-window down:30 \
        --bind ctrl-d:preview-down \
        --bind ctrl-u:preview-up \
        --preview 'GH_FORCE_TTY=$FZF_PREVIEW_COLUMNS gh pr view {1} | bat --color always -l md' |
      awk '{print $1}' |
      tr -d '#' |
      xargs -I {} gh pr view {} --json headRefName |
      jq -r '.headRefName' |
      xargs -I {} git checkout {}
  else
    git checkout -b "$1"
  fi
  exit 0
fi

branch=$(git branch -a | fzf --reverse | tr -d ' ')

if [ ! -z "$branch" ]; then
  if [[ "$branch" == *"remotes/"* ]]; then
    b=$(echo "$branch" | awk -F'/' '{print $3}')
    git checkout -b "$b" "$branch"
  else
    git checkout "$branch"
  fi
fi
