#!/bin/bash

if [ ! -z "$1" ]; then
  if [[ "$1" == "." ]]; then
    git checkout .
  else
    git checkout -b "$1"
  fi
  exit 0
fi

branch=$(git branch -a | fzf --reverse | tr -d ' ')

if [ ! -z "$branch" ]; then
  if [[ "$branch" == *"remotes/"* ]]; then
    b=$(echo "$branch" | awk -F'/' '{print $3}')
    git checkout -b "$b" "$branch"
  else
    git checkout "$branch"
  fi
fi
