#!/bin/bash

if [ -z "$ACCESS_TOKEN" ]; then
  echo "missing ACCESS_TOKEN"
  exit 1
fi

if [ -z "$USER_NAME" ]; then
  echo "missing USER_NAME"
  exit 1
fi

notifications=$(curl -s -u "$USER_NAME:$ACCESS_TOKEN" \
  --get https://ghe/api/v3/notifications \
  | jq '. | map({
    "title": .subject.title,
    "type": .subject.type,
    "url": .subject.url,
    "latest_url": .subject.latest_comment_url
  })')
notifications_length=$(echo $notifications | jq '. | length')

if [[ "$notifications_length" == 0 ]]; then
  echo "notifications is empty"
  exit 0
elif [ -z "$notifications" ]; then
  echo "failed to connect GHE"
  exit 1
fi

if [ -f /tmp/ghe-notifications ]; then
  rm /tmp/ghe-notifications
fi

for i in $(seq 0 $(($notifications_length - 1)))
do
  title=$(echo $notifications | jq -r ".[$i].title")
  notification_type=$(echo $notifications | jq -r ".[$i].type")

  echo "[$notification_type] $title" >> /tmp/ghe-notifications
done

selected_line=$(cat -n /tmp/ghe-notifications | fzf)

if [ -z "$selected_line" ]; then
  exit 1
fi

selected_index=$(($(echo $selected_line | awk '{ print $1 }') - 1))

selected_url=$(echo "$notifications" | jq -r ".[$selected_index].url")
selected_latest_url=$(echo "$notifications" | jq -r ".[$selected_index].latest_url")

if [ "$selected_latest_url" == "null" ]; then
  reacted_url=$(curl -s -u "$USER_NAME:$ACCESS_TOKEN" \
    --get "$selected_url" \
    | jq -r .html_url)
else
  reacted_url=$(curl -s -u "$USER_NAME:$ACCESS_TOKEN" \
    --get "$selected_latest_url" \
    | jq -r .html_url)
fi

if [ ! -z "$reacted_url" ]; then
  open "$reacted_url"
fi

