#!/bin/bash

args=("$@")

for arg in "${args[@]}"; do
  case $arg in
    --proto-root* ) proto_root=${arg##*=};;
    --host* ) host=${arg##*=} ;;
    --authority* ) authority=${arg##*=} ;;
    --package* ) package=${arg##*=} ;;
    --service* ) service=${arg##*=} ;;
    --method* ) method=${arg##*=} ;;
    --meta* ) meta=${arg##*=} ;;
    --message* ) message=${arg##*=} ;;
  esac
done

polyglot_path="$HOME/dev/src/github.com/g-hyoga/dotfiles/tools/bin/polyglot.jar"

echo $polyglot_path

echo "$message" | java -jar -Dorg.slf4j.simpleLogger.defaultLogLevel=error -Djava.util.logging.ConsoleHandler.level=error $polyglot_path \
  --proto_discovery_root="$proto_root" \
  --use_reflection=false \
  call \
  --endpoint="$host" \
  --tls_client_override_authority="$authority" \
  --metadata="$meta" \
  --full_method="$package.$service/$method"

