#!/bin/bash

if [[ "$1" == "mine" ]]; then
  GH_FORCE_TTY='100%' gh issue list --state all --author @me --limit 100 |
    tail -n +4 |
    fzf --ansi \
      --preview-window down:30 \
      --bind ctrl-d:preview-down \
      --bind ctrl-u:preview-up \
      --preview 'GH_FORCE_TTY=$FZF_PREVIEW_COLUMNS gh issue view {1} | bat --color always -l md' |
    awk '{print $1}' |
    tr -d '#' |
    xargs -I {} gh issue view --web {}
else
  GH_FORCE_TTY='100%' gh issue list --state all --limit 100 |
    tail -n +4 |
    fzf --ansi \
      --preview-window down:30 \
      --bind ctrl-d:preview-down \
      --bind ctrl-u:preview-up \
      --preview 'GH_FORCE_TTY=$FZF_PREVIEW_COLUMNS gh issue view {1} | bat --color always -l md' |
    awk '{print $1}' |
    tr -d '#' |
    xargs -I {} gh issue view --web {}
fi

