#!/bin/bash

args=("$@")

if [ "$args" == "create" ]; then
  base_branch=${args[1]:-master}
  gh pr create --base "$base_branch"
elif [ "$args" == "mine" ]; then
  GH_FORCE_TTY='100%' gh pr list --state all --assignee @me --limit 100 | \
    tail -n +4 | \
    fzf --ansi \
      --preview-window down:30 \
      --bind ctrl-d:preview-down \
      --bind ctrl-u:preview-up \
      -m \
      --preview 'GH_FORCE_TTY=$FZF_PREVIEW_COLUMNS gh pr view {1} | bat --color always -l md' |
    awk '{print $1}' |
    tr -d '#' |
    xargs -I {} gh pr view --web {}
elif [[ "$args" =~ ^[0-9]+$ ]]; then
  git fetch upstream "pull/$args/head:pr#$args" \
  && git checkout "pr#$args" \
  || echo "failed to fetch pull request"
else
  GH_FORCE_TTY='100%' gh pr list --state all --limit 100 | \
    tail -n +4 | \
    fzf --ansi \
      --preview-window down:30 \
      --bind ctrl-d:preview-down \
      --bind ctrl-u:preview-up \
      -m \
      --preview 'GH_FORCE_TTY=$FZF_PREVIEW_COLUMNS gh pr view {1} | bat --color always -l md' |
    awk '{print $1}' |
    tr -d '#' |
    xargs -I {} gh pr view --web {}
fi

