#!/bin/bash

args=("$@")

if [ "$args" == "create" ]; then
  base_branch=${args[1]:-master} \
    && result=$(hub pull-request --base "$base_branch") \
    && open "$result" \
    || echo "$result"
elif [[ "$args" =~ ^[0-9]+$ ]]; then
  git branch -D pr \
  && git fetch upstream "pull/$args/head:pr" \
  && git checkout pr \
  || echo "failed to fetch pull request"
else
  tmp=$(hub pr list | fzf) \
    && pullrequest=$(echo $tmp | sed 's/   //g') \
    && number=$(echo "$pullrequest" | awk '{print $1}' | sed 's/#//g') \
    && echo "open $pullrequest" \
    && hub browse -- "pull/$number" \
    || echo ""
fi

