name: nvim-status

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: make nvim
      run: make nvim
    - name: check health
      run: ./nvim/bin/check-health.sh
