extra-keys = [['ESC','TAB','CTRL','ALT','-','LEFT','DOWN','UP','RIGHT'], \
              ['FN','CTRL','ALT','HOME','END','PGUP','PGDN','|','BKSP']]

terminal-transcript-rows = 5000

volume-keys = volume

bell-character = ignore
